# Generated by Django 3.0.4 on 2020-05-04 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='user',
        ),
        migrations.RemoveField(
            model_name='poems',
            name='date',
        ),
        migrations.RemoveField(
            model_name='poems',
            name='user',
        ),
    ]
