# Generated by Django 3.0.4 on 2020-05-04 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20200504_0336'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
        migrations.RenameModel(
            old_name='Poems',
            new_name='Poem',
        ),
    ]
