# Generated by Django 3.0.4 on 2020-05-04 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20200504_0721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poem',
            name='poem',
            field=models.TextField(max_length=10000),
        ),
    ]
