# Generated by Django 3.0.4 on 2020-05-04 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20200504_0723'),
        ('main_app', '0007_poem_user'),
    ]

    operations = [
    ]
